Add VAT fields in transactions
scharrier/qonto-ruby pull request #3
Opened 2019-01-26 18:25 UTC by tpayet

2019-01-29 16:50 UTC, scharrier commented on lib/qonto/model/transaction.rb
> +      attr_accessor :amount, :amount_cents, :local_amount, :local_amount_cents,
👍 for calling `attr_accessor` only once, but I think that I prefer to keep one attribute / line, as it seems to be easier to read. WDYT?

Btw, don't you think we should alpha sort attributes?

2019-01-29 16:52 UTC, scharrier reviewed
Thanks for your contribution :)

LGTM beside a small comment. As this part isn't tested at all, would you mind adding specs to test that returned models has the good attributes? (If this is a problem I'll add these tests)

2019-01-31 13:26 UTC, tpayet commented on lib/qonto/model/transaction.rb
> +      attr_accessor :amount, :amount_cents, :local_amount, :local_amount_cents,
I corrected it with one `attr_accessor` per line and alpha sorted them

2019-01-31 13:28 UTC, tpayet commented
Pleas tell me if the spec I wrote is okay for you

2019-01-31 13:40 UTC, scharrier requested changes
If you agree with me, we could do the 2 changes I proposed and I'll merge and release a new version. Thanks again :)

2019-01-31 13:40 UTC, scharrier commented on spec/qonto/client_spec.rb
> +      expect(response.first.instance_variables).to eq(%i[@amount
I think that what we really want to test here, is that each attribute present in the JSON response is accessible through the model interface, and that it has been set at the good value.

What do you think of instead adding a test per attribute we want to test ? This is a but longer to write, but may be safer on a long term point of view (= we are sure that everything is present and correctly set). And maybe easier to read.

Example:
```
expect(response.first.amount).to eq(0.42)
expect(response.first.amount_cents).to eq(42)
# ...
```

Do you agree ?

2019-01-31 13:40 UTC, scharrier commented on spec/qonto/client_spec.rb
> +require 'byebug'
Why do we add that line ?

2019-02-04 08:30 UTC, merged

2019-02-04 08:41 UTC, scharrier commented
Thanks again for your help @tpayet, I just released a new version of the gem (0.3.0).